version: '3'
services:
  #
  # database by mariadb
  #
  db:
    container_name: db
    image: mariadb
    build: ./db
    volumes:
      - template_webapp_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: template_webapp_db
      MYSQL_PASSWORD: template_webapp_db
      MYSQL_DATABASE: template_webapp_db
    networks:
      - backend

  #
  # phpMyAdmin
  #
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - template_webapp_phpmyadmin:/sessions
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - backend
    depends_on:
      - db

  #
  # smtp server by mailhog
  #
  smtp:
    container_name: smtp
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MAIL_HOST: smtp
      MAIL_PORT: 1025
    networks:
      - backend

  #
  # server application
  #
  backend-app:
    container_name: backend-app
    build: ../template_webapp_server
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - db
      - smtp

  #
  # client application
  #
  frontend-app:
    container_name: frontend-app
    build: ../template_webapp_client
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - backend-app

networks:
  backend: null

volumes:
  template_webapp_db: null
  template_webapp_phpmyadmin: null
